build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.11"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.11"
  armhf: "ghcr.io/home-assistant/armhf-base-python:3.11"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.11"

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: TfGM Tram Analyzer"
  org.opencontainers.image.description: "Scrapes TfGM Metrolink live departure boards and exposes tram timing data to Home Assistant."
  org.opencontainers.image.source: "https://github.com/johnfevre/tfgm-tram-analyzer-ha-add-on"
  org.opencontainers.image.licenses: "MIT"
